[package]
name = "wasm-deploy"
version = "0.1.0"
authors = ["Eric Woolsey<ewoolsey@ualberta.ca>"]
edition = "2021"
homepage = "https://nept.finance"

[features]
default = ["wasm_cli"]
wasm_cli = []

[dependencies]
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
clap = { version = "4.0.18", features = ["derive", "string"] }
schemars = "0.8"
serde_json = "1.0"
lazy_static = "1.4.0"
clap_complete = "4.0.3"
inquire = "0.5.2"
strum = "0.24.1"
thiserror = "1.0.37"

tendermint-rpc = { version = "0.25.0", default-features = false, features = ["http-client"] }
cosmrs = { version = "0.9.0", features = ["dev", "cosmwasm"] }
tokio = { version = "1.21.2", default-features = false }
async-recursion = "1.0.0"
cosmos-sdk-proto = "0.14.0"
keyring = "1.2.0"
cosm-orc = "=2.7.0"
colored = "2.0.0"
colored_json = "3.0.1"
interactive-parse = "0.1.0"

[dev-dependencies]
faux = "0.1.7"

# TODO: leaving this here so I remember it later
# tmkms = { version = "0.12.2", features = ["ledgertm"] }