[package]
name = "wasm-deploy"
version = "0.1.0"
authors = ["Eric Woolsey<ewoolsey@ualberta.ca>"]
edition = "2021"
homepage = "https://nept.finance"

[dependencies]
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
clap = { version = "4.0.18", features = ["derive", "string"] }
serde_json = "1.0"
lazy_static = "1.4.0"
clap_complete = "4.0.3"
inquire = "0.4.0"
clap-interactive = "0.1.3"
strum = "0.24.1"

[dev-dependencies]
tokio = "1.21.2"
tendermint-rpc = { version = "0.25.0", features = ["http-client"] }