[package]
name = "wasm-deploy-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
wasm-deploy = { path = "../wasm-deploy" }
